### ISSUE TITLE
Scoring on level 39 

### ISSUE THREAD

**Issue by EmilyPage** [ocadotechnology/rapid-router#705]
The scoring on level 39 appears to work off logic from a previous level, that is, the only way to get a perfect score is to not use the "if" loops which have just been taught. 
![screen shot 2015-11-11 at 17 44 22](https://cloud.githubusercontent.com/assets/15234751/11098848/9b4c32fe-889f-11e5-9178-7d8a14f1fa0b.png)

**Comment by pawelkrupinski** [comment]
Thanks for letting us know!
Encouraging students not to use "if" blocks on this level is intentional, as described in the teacher packs:
http://storage.googleapis.com/codeforlife-assets/KS2/program_solutions/program_solutions_table.pdf

**Comment by CelineBoudier** [comment]
A teacher wrote us this week to tell us they find it inconsistent. There is already a later level which deals with not using the if statement in a better way, as in level 39 all the explanations in the hints and the introduction explicitly ask the students to modify the generic solution. So this should be solved: either the hints are changed, or the repeat X time should be removed from the available blocks...

**Comment by mrniket** [comment]
Still relevant, maybe we should make a new level 39 which incorporates the `if` statement

**Comment by lawrenceweetman** [comment]
This is still an issue. 

It's problematic for a few reasons:

1. It isn't clear from the instructions that it doesn't necessarily expect you to use an if-statement.
2. Later instructions seem to suggest that you should consider an alternative to if-statements (either 40 or 41), yet there IS an expectation that those are resolved with if-statements.
3. The "help" hint still says you can solve it with a modification to the generalised algorithm.

I think this could be resolved in a satisfactory way without necessarily rewriting the level, @mrniket. If the instructions and help hint wording was changed, I think it'd be fine.

It did cause some confusion and frustration in our household. Have you had any other feedback on this?

**Comment by mrniket** [comment]
Thanks for the suggestions @lawrenceweetman. We haven't had anything more recently on this but it's still an issue. How about if we change the instructions to: 

> Can you use the 'general algorithm' here so that the van takes a shorter route?
Or maybe there's a more efficient way?
Keep an eye on the fuel level - try to use as little as possible.

With the hint: 

> Uh oh, moving around the blocks in your 'general algorithm' might not be the most efficient solution.
How about creating a simple solution without 'if statements' that will help the van reach the house?

Would something like that work @rdcruzCFL?

**Comment by sebp999** [comment]
Changes pushed to https://github.com/ocadotechnology/rapid-router/pull/1129

**Comment by rdcruzCFL** [comment]
I think that is better, @mrniket
